import type { Metadata } from "next";
import LegalPage from "@/components/LegalPage";
import { SITE_NAME, og } from "@/lib/site";

export const metadata: Metadata = {
  title: "Terms of Use",
  description:
    "The terms that govern this website, its free tools and printable templates, and how our services relate to it. Draft pending attorney review.",
  openGraph: og("/terms"),
};

export default function TermsPage() {
  return (
    <LegalPage
      title="Terms of Use"
      lastUpdated="July 2026"
      sections={[
        {
          heading: "Acceptance of these terms, and changes to them",
          paragraphs: [
            `These Terms of Use govern your use of this website, published by ${SITE_NAME} ("we," "us," "our"). By using the site — reading its pages, running its free tools, or printing its templates — you accept these terms. If you do not accept them, please do not use the site.`,
            "We may revise these terms from time to time as the site grows or the law requires. The “Last updated” date above reflects the current version, and continued use of the site after a change means you accept the revised terms. We will not apply changes retroactively to anything you already did under an earlier version.",
          ],
        },
        {
          heading: "Who this site is for",
          paragraphs: [
            "This site is written for parents and guardians, educators, and students. Students under 18 are welcome to use the free tools — that is what many of them are for — and should do so with a parent's or guardian's awareness.",
            "The site has no accounts and no logins, and there is nowhere to enter personal information other than two optional forms: the contact form and the newsletter signup, both intended for adults. The free tools run entirely in your browser and do not ask for, transmit, or keep anything you type into them.",
          ],
        },
        {
          heading: "Educational purposes only — not professional advice",
          paragraphs: [
            "Everything on this site — articles, guided toolkits, interactive tools, study plans, printable templates — is general educational information. It is not medical, psychological, or legal advice, and it is not legal advice about special education rights or procedures, which vary by state and district.",
            "Plans and suggestions generated by the tools are informational starting points built from the answers you tap in — they don't know your child, your classroom, or your school. Verify important decisions with your school and with qualified professionals who do.",
          ],
        },
        {
          heading: "Free interactive tools",
          paragraphs: [
            "The site's free interactive tools — including the Study Coach, the Study Plan Builder, the SAT Schedule Builder, the guided toolkits, and the service-fit chooser — run entirely in your web browser. Nothing you type or tap in them is sent to us or stored anywhere; closing the tab clears it.",
            "The Study Coach and the guided toolkits are scripted, guided tools: they follow a fixed decision tree we wrote, and your taps choose a path through it. They do not generate content and do not learn from or retain what you enter.",
          ],
        },
        {
          heading: "Printable templates",
          paragraphs: [
            "The printable templates are provided as-is for classroom and home use. They are generic organizational aids — not official records — and they don't replace whatever documentation your school or district requires. Follow the privacy notes printed on the templates when writing student information on them.",
          ],
        },
        {
          heading: "Links to outside resources",
          paragraphs: [
            "Our tools and articles link to free third-party educational resources, such as official test-prep and practice sites. Those sites are not ours: we don't control their content, availability, or policies, and a link is not an endorsement of everything a site does. Their own terms and privacy policies apply once you're there.",
          ],
        },
        {
          heading: "Our services are separate from this website",
          paragraphs: [
            "We offer paid educational services — tutoring, college counseling, and SETSS — that are described on this site but governed entirely by separate written engagement agreements signed by both sides. Nothing on this website, including using its free tools, contacting us, or receiving a suggestion from the service-fit chooser, creates a client, provider, or advisory relationship with us. That relationship begins only when an engagement agreement says it does.",
          ],
        },
        {
          heading: "Intellectual property and your license to use it",
          paragraphs: [
            "The content of this site — its text, tools, templates, graphics, and design — belongs to us or is used with permission. We built it to be used, so:",
          ],
          list: [
            "You may print, download, and use the templates and the plans our tools generate for your own personal, family, or classroom use, including sharing copies within your school.",
            "You may link to any page on this site.",
            "You may not sell, relicense, or commercially redistribute the site's content, templates, or tool outputs, present them as your own work, or remove our name from them.",
          ],
        },
        {
          heading: "Acceptable use",
          paragraphs: ["When using this site, you agree not to:"],
          list: [
            "Attempt to disrupt, overload, or interfere with the site or the hosting it runs on.",
            "Use automated tools to scrape or republish the site's content at scale.",
            "Submit forms with false identity information, spam, or content that is unlawful or abusive.",
            "Use the site or its content in any way that violates applicable law.",
          ],
        },
        {
          heading: "Disclaimer of warranties",
          paragraphs: [
            "DRAFT LANGUAGE — FOR ATTORNEY REFINEMENT: The site and everything on it are provided “as is” and “as available,” without warranties of any kind, express or implied — including implied warranties of merchantability, fitness for a particular purpose, and non-infringement. We do not warrant that the site will be uninterrupted or error-free, or that its educational content fits any particular student's situation.",
          ],
        },
        {
          heading: "Limitation of liability",
          paragraphs: [
            "DRAFT LANGUAGE — FOR ATTORNEY REFINEMENT: To the fullest extent permitted by law, we will not be liable for indirect, incidental, special, or consequential damages arising out of your use of this free website — including decisions made in reliance on its educational content or tool outputs. Some jurisdictions do not allow certain limitations, so parts of this section may not apply to you. Liability connected to our paid services is addressed in each engagement agreement, not here.",
          ],
        },
        {
          heading: "Dispute resolution",
          paragraphs: [
            "[ATTORNEY TO COMPLETE. This section is intentionally left undrafted: choices about arbitration, class-action waivers, venue, and fee-shifting are consequential and jurisdiction-specific, and should be made with counsel rather than templated. Until it is completed, no arbitration requirement or similar provision is part of these terms.]",
          ],
        },
        {
          heading: "Governing law",
          paragraphs: [
            "These terms are governed by the laws of the State of New York, without regard to conflict-of-law principles. [ATTORNEY TO CONFIRM governing law and venue.]",
          ],
        },
        {
          heading: "How to reach us",
          paragraphs: [
            `Questions about these terms? Reach us through the contact page on this site — a real person at ${SITE_NAME} reads every message.`,
          ],
        },
      ]}
    />
  );
}
